### ISSUE TITLE
Request failed, status 403

### ISSUE THREAD

**Issue by mdeniz63** [privet-kitty/obsidian-blogger#2]
When I try to save Profile I get error "Request failed, status 403" and i can not save and use program.

Note : I have created OAUTH Client ID and Validated successfully.

**Comment by privet-kitty** [comment]
@mdeniz63 Thank you for your feedback! I have two points to make sure:

1. Which do you use, Mobile (Android?) or Desktop? 
2. Before creating OAuth2 Client ID, you have completed some procedures on the Google console, such as creating a project or composing the OAuth2 consent screen, haven't you? Could you please explain what you did?

You might be the first user of this plugin other than myself, and I'll need to add more description about the settings.

**Comment by mdeniz63** [comment]
I have created a project and composing the OAuth2 consent screen. I have Oauth Client ID and Secret key and I tried to authorize and validate it from obsidian. I make it for Desktop application. 
I get error only after push save (create) profile button.

**Comment by privet-kitty** [comment]
@mdeniz63 Thanks. One thing that slipped out of my document would be _enabling the Blogger API_ in the project, which should be like the following screenshot.

![image](https://github.com/privet-kitty/obsidian-blogger/assets/10072062/fd3755dc-d16a-4b06-a1b0-b89b9302ba8b)

Is it enabled also in your project?

**Comment by mdeniz63** [comment]
Thanks I didnt create **Blogger Api** thanks for your help.
I plan to use plugin and test if i find something i can share.
Best regards
