### ISSUE TITLE
Request : Update published post 

### ISSUE THREAD

**Issue by mdeniz63** [privet-kitty/obsidian-blogger#3]
Hello I have tried and publish a post as draft and later i try to update same from obsidian.
Not updated postID . I get error Request failed 404 .
If update published post it will be best for plugin.

**Comment by privet-kitty** [comment]
Thank you for your feedback.

> I get error Request failed 404 .

I guess the typical cause for 404 would be that the post no longer exists in the Blogger side and this plugin tried to update the non-existent post. Is your post actually accessible from your [dashboard](https://www.blogger.com)? If not, you'll need to remove `postId` from the front matter and publish it again.

**Comment by mdeniz63** [comment]
I respect your decicion but if not update existing post.
But if it will be more valuable posible to ubdate existing post from obsidian.
Because if its posible to send and update existing blog post.You can controll all posts from obsidian and update them.
Note : My blog is https://mahmutdeniz.blogspot.com/

**Comment by privet-kitty** [comment]
You've got it wrong. You _can_ update an existing post using this plugin. 404 means that the post of `postId` no longer exists in your blog for some reason.

**Comment by mdeniz63** [comment]
Hımm ok. 👍
